[build]
  command = "pnpm build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Redirection SPA pour les routes de l'application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
